### ISSUE TITLE
failed to load / install

### ISSUE THREAD

**Issue by Natotela** [Fannovel16/FN16-ComfyUI-nodes#3]
when trying to install
```
ComfyUI_windows_portable\python_embeded\python.exe .\install.py
----------INSTALLING DEPENDENCIES----------
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

when loading comfyUI

```(IMPORT FAILED): F:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\FN16-ComfyUI-nodes```

```
  File "F:\...\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1304, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\...\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\FN16-ComfyUI-nodes\\__init__.py'

Cannot import F:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\FN16-ComfyUI-nodes module for custom nodes: [Errno 2] No such file or directory: 'F:\\...\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\FN16-ComfyUI-nodes\\__init__.py'
Traceback (most recent call last):
  File "F:\...\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1304, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\trNodes\__init__.py", line 1, in <module>
    import custom_nodes.comfy_nodes_trojblue.image_layering as image_layering
ModuleNotFoundError: No module named 'custom_nodes.comfy_nodes_trojblue'
```

**Comment by Fannovel16** [comment]
This is not a custom nodes repo lol
